---
- name: Teste de conexão com servidores via ICMP
  hosts: all
  gather_facts: False
  
  pre_tasks:
    - debug:
        msg: Iniciando teste de ICMP

  roles:
    - ping

  post_tasks:
    - debug:
        msg: Encerrando teste de ICMP