---
# tasks file for server_check
  - name: Executando teste
    ping:
    register: result

  # - name: Gravando saída
  #   set_stats:
  #     data:
  #       resultado: "{{ (ping_result.stdout|from_json).ping }}"

  - name: Debugando ping
    debug:
      msg: "{{ (result.stdout|from_json) }}"