---
# tasks file for server_check
  - name: Executando teste
    ping:
    register: ping_result

  - name: Gravando saída
    set_stats:
      data:
        resultado: "{{ ping_result.ping }}"

  - name: Debugando ping
    debug:
      var: resultado