---
# tasks file for server_check
  - name: Executando teste
    ping:
    register: ping_result

  - name: Gravando saída
    set_stats:
      data:
        resultado: "{{ ping_result.ping }}"

  - name: Incluindo captura de hostname
    include_role:
      name: hostname

  # - name: Debugando ping
  #   debug:
  #     msg: "{{ (result.stdout|from_json) }}"